### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sayho93** [psyho-pw/jormungandr#5]
- [x] core-time 설정
- [x] max respond 설정
- [x] 메세지 게시자 제외
- [x] serve statistics by slash command
- [x] **error handling 관심사 분리**
- [x] respond시 ~~원본 메세지 작성자에 의해 생성된~~ 이전 메세지는 모두 응답한 것으로 간주
- [x] 스레드 내 댓글에 대한 반응은 반응에 포함하지 않도록 처리 - 작동 하나, 에러로 인식하기에 개선 필요
- [ ] 이모지나 스레드 내 댓글을 썼다가 삭제하면 반응 하지 않은 것로 간주
- [ ] core time 설정 UI 변경
- [ ] slash command에 권한 부여
- [ ] batch시 정보 불일치 row update - partially done
- [ ] 데이터 캐싱해서 처리 속도 올리면 좋을듯
